[build-system]
requires = [
    "setuptools >= 44",
    "wheel",
    "versioneer-518",
]
build-backend = "setuptools.build_meta"

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pycln]
all = true
